### ISSUE TITLE
Input data structure for beeswarm plots

### ISSUE THREAD

**Issue by xsvato01** [ewels/MultiQC_TestData#243]
Hi, I am unable to produce any custom beeswarm plots. I tried to plot one of your test data files located at /with_config/table_headerconfig. From what I read on https://multiqc.info/docs/#beeswarm-plots-dot-plots I supposed the input data structure should be the same as for tables. Yet, when I edit the multiqc_config.yaml to "beeswarm" I am getting the following:
```
custom_content | Not able to parse custom data in sequencing_stats.txt
```

REGEX:
multiqc_config.yaml
```
custom_data:
    sequencing_stats:
        plot_type: 'beeswarm'
sp:
    sequencing_stats:
        fn: 'sequencing_stats.txt'
```
sequencing_stats.txt
```
Sample Name	Total reads	MBp	%Q30
samp_1	10293	3238472	87
samp_2	18892	3218892	74
samp_3	16384	2982834	88
```

Any ideas would me much appreciated!
